# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Installs packages selected in the netinstall step via pacman.
---
backend: pacman

update_db: true

pacman:
  default_install_operation: install
  install_options:
    - "--noconfirm"
    - "--needed"
  remove_options:
    - "--noconfirm"
